/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.telas;

/**
 *
 * @author WINDOWS 10 PRO
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BLogin = new javax.swing.JButton();
        BCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BISair1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BiSair2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(912, 509));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Starting");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(120, 20, 130, 30);

        BLogin.setBackground(new java.awt.Color(255, 255, 255));
        BLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BLogin.setForeground(new java.awt.Color(0, 0, 0));
        BLogin.setText("Login");
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        jPanel2.add(BLogin);
        BLogin.setBounds(100, 150, 130, 28);

        BCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        BCadastrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        BCadastrar.setText("Sign Up");
        BCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(BCadastrar);
        BCadastrar.setBounds(100, 270, 130, 28);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Or");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(150, 220, 37, 16);

        BISair1.setBackground(new java.awt.Color(255, 255, 255));
        BISair1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BISair1.setForeground(new java.awt.Color(0, 0, 0));
        BISair1.setText("Cancel");
        BISair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BISair1ActionPerformed(evt);
            }
        });
        jPanel2.add(BISair1);
        BISair1.setBounds(300, 430, 74, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 10, 400, 480);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Icone");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 20, 110, 50);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Texto Texto Texto Texto Texto Texto");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 130, 270, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Texto Texto Texto Texto Texto Texto");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 200, 270, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Texto Texto Texto Texto Texto Texto");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(520, 160, 270, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Texto Texto Texto Texto Texto Texto");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(520, 90, 270, 17);

        BiSair2.setBackground(new java.awt.Color(0, 0, 0));
        BiSair2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BiSair2.setForeground(new java.awt.Color(255, 255, 255));
        BiSair2.setText("<--");
        BiSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiSair2ActionPerformed(evt);
            }
        });
        jPanel1.add(BiSair2);
        BiSair2.setBounds(0, 0, 72, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BiSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiSair2ActionPerformed
        dispose();
    }//GEN-LAST:event_BiSair2ActionPerformed

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        TelaDeLogin tlg = new TelaDeLogin();
       tlg.setVisible(true);
       dispose();
    }//GEN-LAST:event_BLoginActionPerformed

    private void BCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarActionPerformed
         TelaDeCadastro tcd = new TelaDeCadastro();
       tcd.setVisible(true);
       dispose();
    }//GEN-LAST:event_BCadastrarActionPerformed

    private void BISair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BISair1ActionPerformed
        dispose();
    }//GEN-LAST:event_BISair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCadastrar;
    private javax.swing.JButton BISair1;
    private javax.swing.JButton BLogin;
    private javax.swing.JButton BiSair2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private TelaDeLogin TelaDeLogin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
